name: Build and Deploy Flutter App

# Trigger the workflow whenever code is pushed or a pull request is made
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build for Android, Windows, and Linux
    runs-on: ${{ matrix.os }}  # Run on different OS environments

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, ubuntu-22.04]
        # Include other operating systems if needed

    steps:
      - uses: actions/checkout@v4  # Check out the code
      - uses: subosito/flutter-action@v2.13.0
        with:
          channel: 'stable'
          cache: true
      - run: flutter --version

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # Or another distribution like 'zulu'
          java-version: '12.x'
          cache: gradle

      - name: Configure Flutter
        run: flutter config --enable-windows-desktop --enable-linux-desktop --enable-macos-desktop

      - name: Get Dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: echo $KEYSTORE_BASE64 | base64 --decode > android/app/keystore.jks

      - name: Configure Signing
        run: echo "storeFile=keystore.jks
          storePassword=$KEYSTORE_PASSWORD
          keyAlias=$KEY_ALIAS
          keyPassword=$KEY_PASSWORD
          " > key.properties

      - name: Build Android Release APK
        if: matrix.os == 'ubuntu-22.04'
        run: flutter build apk --release

      - name: Build Windows App
        if: matrix.os == 'windows-latest' # Build Windows on Windows
        run: flutter build windows

      - name: Build Linux App
        if: matrix.os == 'ubuntu-latest' # Build Linux on macOS
        run: | 
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev libunwind-dev
          flutter build linux

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            build/app/outputs/flutter-apk/app-release.apk # Android APK
            build/windows/runner/Release/*.exe         # Windows executable
            build/linux/x64/release/bundle/*             # Linux files

